### ISSUE TITLE
Jenkins complaining about docker image replication

### ISSUE THREAD

**Issue by danbryce** [SD2E/xplan#2]
```+ docker run -t -d --rm --name sd2-sbcl mdehavensift/sbcl:1.4.0
docker: Error response from daemon: Conflict. The container name "/sd2-sbcl" is already in use by container "dda32ef62750e57342b6744c3b5b0d2f62b52235fb9760f986690f9a3e595de8". You have to remove (or rename) that container to be able to reuse that name.
See 'docker run --help'.```

**Comment by mdehavensift** [comment]
Refactored Jenkins build command to only use a unnamed docker container which is removed after the container exits. Docker image replicate is no longer a problem with the jenkins build.

New jenkins build command:
```
cd code

sh get_externals.sh

docker run --security-opt seccomp=unconfined -t --rm -v "$(readlink -f .)":/code \
mdehavensift/sbcl_user:1.4.0 bash -c "cp -r /code ~/code && ~/code/tests/run-tests.sh"
```

The security-opt setting was added due to the docker failing to run SBCL with the following error:
`Couldn't re-execute SBCL with proper personality flags (/proc isn't mounted? setuid?)`

Suggested fix source: https://github.com/dimitri/pgloader/issues/511

The copy of /code to ~/code is done to avoid working in the mounted directory. This can cause permission problems sometimes when a file is created in the mounted volume.
